### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by shazron** [adobe/adobe-fetch#19]
Does this library work in the browser? I notice the use of `node-persist` which implies probably not. Can you clarify? Thanks :)

**Comment by ittaibaratz** [comment]
Hi @shazron , in its current state, the library is not designed to work in the browser because it generates the JWT token itself which means it needs access to the private key.

From a security perspective, I don't see how this can be done in the browser without exposing the private key to the end users.

To make it work in the browser, we can add an option to get the access token from an external source rather than generate it by the library. In this case, there would still need to be a server side component providing the access token, or alternative a non-JWT auth workflow which will get the access token through the browser. Is this matching your use case?

**Comment by macdonst** [comment]
@ittaibaratz we could enhance the `auth` part of the config object to optionally take a Bearer token but that would lose the ability to automatically reconnect. Thoughts?

**Comment by ittaibaratz** [comment]
@macdonst yep, that was my thinking. Either provide a bearer token, or provide an async function that would return a token (Which would solve for reconnect). 

That said, I looked at https://github.com/adobe/adobeio-cna-core-campaign-standard/issues/21 and I dont have enough context to understand the problem which this is supposed to solve?

**Comment by shazron** [comment]
@ittaibaratz thanks! I'm evaluating this purely for 1) the `fetch` functionality and 2) logging of requests (`node-fetch` doesn't do logging). @meryllblanchet brought this repo to my attention. Bonus is the auth stuff, and also dogfooding an Adobe-created library. The requirements of the sdk we are building is that it has to also work in the browser.

**Comment by ittaibaratz** [comment]
@shazron - This library is intended for calling Adobe APIs. It adds specific headers to the requests. Are you just looking to do a logged fetch which will fetch resources other than Adobe APIs?

**Comment by shazron** [comment]
@ittaibaratz our SDK is definitely only calling Adobe APIs (for example in the linked issue, calling Adobe Campaign Standard REST API), and we do set `Authorization` (IMS access token) and `X-Api-Key` headers as well. 

For a few functions in the SDK, we need to do a generalized `fetch` (the URLs are still to Adobe APIs) because of the way the Adobe Campaign Standard REST API works -- some calls return absolute urls that devs need to `POST` to.

**Comment by ittaibaratz** [comment]
@shazron got it. Btw, adobe-fetch does use node-fetch under the hood. Though for browser mode I guess we can use the browser's native fetch.

**Comment by ittaibaratz** [comment]
Writing down requirements so we can look into implementing this later:

**Browser support**

1. Single JS file (i.e. using webpack)
2. Use native fetch and not node-fetch in browsers
3. In browser mode, access token will be provided through the config. Either directly or via an async function. If function - It will be called for token renewals. 
4. Storage will be automatically disabled as we don't own the access token management in a browser environment
5. Add Selenium to our unit tests

**Comment by shazron** [comment]
I ended up using [cross-fetch](https://www.npmjs.com/package/cross-fetch) for now. Uses [node-fetch](https://www.npmjs.com/package/node-fetch) when under `node`, and [whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch) for the browser.

**Comment by ittaibaratz** [comment]
No longer needed, closing.
